### ISSUE TITLE
Error When Doing A Numeric Search

### ISSUE THREAD

**Issue by cstevensjr** [LostKobrakai/InputfieldChosenSelect#1]
I created a page field and used this module as the input.  I then added the created field "crms_tags" to the standard PW search.php template.

Everything works great until I search on a tag that is a numeric value.  I then receive the following error:

![search-error1](https://cloud.githubusercontent.com/assets/7488817/6236490/dc5729c0-b69f-11e4-8229-a5dab71efeac.png)

Once I remove this field "crms_tags" from the search.php template, there are no more problems.  I can search for text or numeric information.

**Comment by LostKobrakai** [comment]
My module is only an inputfield. It does hardly more than the core asmselect from the backand side. Most of the differences are just javascript ans styling. So this shouldn't be a error of my consern. Have you tried the leaving the pagefield in the search with just another inputfield selected?

**Comment by cstevensjr** [comment]
I'll try that. Thanks for the suggestion.

**Comment by cstevensjr** [comment]
You were correct, I am getting this with other inputfields selected.  I will close this issue and bring it up in the main PW issue tracker.  Thanks for your help.
