### ISSUE TITLE
Support for standard-selects (not multi-selects)

### ISSUE THREAD

**Issue by thomasaull** [LostKobrakai/InputfieldChosenSelect#2]
It would be a great addition, if this module could support single-select-inputfields (see first one for an example: http://harvesthq.github.io/chosen/) if the inputfield-setting is limited to single-page.

**Comment by LostKobrakai** [comment]
I'll take a look at it.

**Comment by LostKobrakai** [comment]
In the meantime, there's also InputfieldPageAutocomplete.

**Comment by thomasaull** [comment]
Thanks :)

**Comment by LostKobrakai** [comment]
Please have a look at the dev branch of the module. Will add some styles later and merge it to master if there're no issues.

**Comment by thomasaull** [comment]
Tested it just now, works like a charm :) Thx for the addition!
