### ISSUE TITLE
ProcessWire 3.0.22 - won't save placeholder text

### ISSUE THREAD

**Issue by outflux3** [LostKobrakai/InputfieldChosenSelect#5]
the placeholder text field will no longer save for this (newest) version of PW...
Same thing happening on my inputfield, but can't figure out why...

**Comment by outflux3** [comment]
looks like this was caused by the module not setting default values in a construct; Ryan has made a change to the core to allow for this so things should work again in the newest dev

**Comment by LostKobrakai** [comment]
Did you check it? If not I'll leave this open a bit longer.

**Comment by outflux3** [comment]
yep, looks good on 3.0.23 devns
