### ISSUE TITLE
InputfieldChosenSelectMultiple / InputfieldChosenSelect doesn't renders in repeater

### ISSUE THREAD

**Issue by ibrahimovfuad** [LostKobrakai/InputfieldChosenSelect#6]
I am using your plugin and there is an issue when i am using InputfieldChosenSelectMultiple or InputfieldChosenSelect in repeater.
if I am using InputfieldChosenSelectMultiple it renders html multiple select box. The same problem with InputfieldChosenSelect but it renders html select.
![selection_011](https://cloud.githubusercontent.com/assets/10096764/20497306/0fd655b2-b042-11e6-842b-4e7008e60717.png)
There are no scripts of chosen.jquery plugin in the DOM tree. But when i am using your plugin without repeater it works fine without issues.
I think problem is in dynamic rendering of field.

**Comment by thomasaull** [comment]
I've got the same problem… As a workaround you can set the "repeater dynamic loading" in your fieldsettings > input to "off"

**Comment by LostKobrakai** [comment]
https://github.com/LostKobrakai/InputfieldChosenSelect/pull/8
